#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamMemQuanLyKho1._1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyKho")]
	public partial class DataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaccount(account instance);
    partial void Updateaccount(account instance);
    partial void Deleteaccount(account instance);
    partial void Insertbophannv(bophannv instance);
    partial void Updatebophannv(bophannv instance);
    partial void Deletebophannv(bophannv instance);
    partial void Inserthanghoa(hanghoa instance);
    partial void Updatehanghoa(hanghoa instance);
    partial void Deletehanghoa(hanghoa instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertkho(kho instance);
    partial void Updatekho(kho instance);
    partial void Deletekho(kho instance);
    partial void Insertnhacungcap(nhacungcap instance);
    partial void Updatenhacungcap(nhacungcap instance);
    partial void Deletenhacungcap(nhacungcap instance);
    partial void Insertnhomhanghoa(nhomhanghoa instance);
    partial void Updatenhomhanghoa(nhomhanghoa instance);
    partial void Deletenhomhanghoa(nhomhanghoa instance);
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    partial void Insertphieuxuat(phieuxuat instance);
    partial void Updatephieuxuat(phieuxuat instance);
    partial void Deletephieuxuat(phieuxuat instance);
    partial void Insertthukho(thukho instance);
    partial void Updatethukho(thukho instance);
    partial void Deletethukho(thukho instance);
    #endregion
		
		public DataClassDataContext() : 
				base(global::PhamMemQuanLyKho1._1.Properties.Settings.Default.QuanLyKhoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account> accounts
		{
			get
			{
				return this.GetTable<account>();
			}
		}
		
		public System.Data.Linq.Table<bophannv> bophannvs
		{
			get
			{
				return this.GetTable<bophannv>();
			}
		}
		
		public System.Data.Linq.Table<hanghoa> hanghoas
		{
			get
			{
				return this.GetTable<hanghoa>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<kho> khos
		{
			get
			{
				return this.GetTable<kho>();
			}
		}
		
		public System.Data.Linq.Table<nhacungcap> nhacungcaps
		{
			get
			{
				return this.GetTable<nhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<nhomhanghoa> nhomhanghoas
		{
			get
			{
				return this.GetTable<nhomhanghoa>();
			}
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<phieuxuat> phieuxuats
		{
			get
			{
				return this.GetTable<phieuxuat>();
			}
		}
		
		public System.Data.Linq.Table<thukho> thukhos
		{
			get
			{
				return this.GetTable<thukho>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtk;
		
		private string _taikhoan;
		
		private string _matkhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtkChanging(int value);
    partial void OnidtkChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtk", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idtk
		{
			get
			{
				return this._idtk;
			}
			set
			{
				if ((this._idtk != value))
				{
					this.OnidtkChanging(value);
					this.SendPropertyChanging();
					this._idtk = value;
					this.SendPropertyChanged("idtk");
					this.OnidtkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bophannv")]
	public partial class bophannv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mabophan;
		
		private string _tenbophan;
		
		private EntitySet<thukho> _thukhos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabophanChanging(string value);
    partial void OnmabophanChanged();
    partial void OntenbophanChanging(string value);
    partial void OntenbophanChanged();
    #endregion
		
		public bophannv()
		{
			this._thukhos = new EntitySet<thukho>(new Action<thukho>(this.attach_thukhos), new Action<thukho>(this.detach_thukhos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabophan", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mabophan
		{
			get
			{
				return this._mabophan;
			}
			set
			{
				if ((this._mabophan != value))
				{
					this.OnmabophanChanging(value);
					this.SendPropertyChanging();
					this._mabophan = value;
					this.SendPropertyChanged("mabophan");
					this.OnmabophanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbophan", DbType="VarChar(20)")]
		public string tenbophan
		{
			get
			{
				return this._tenbophan;
			}
			set
			{
				if ((this._tenbophan != value))
				{
					this.OntenbophanChanging(value);
					this.SendPropertyChanging();
					this._tenbophan = value;
					this.SendPropertyChanged("tenbophan");
					this.OntenbophanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bophannv_thukho", Storage="_thukhos", ThisKey="mabophan", OtherKey="mabophan")]
		public EntitySet<thukho> thukhos
		{
			get
			{
				return this._thukhos;
			}
			set
			{
				this._thukhos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thukhos(thukho entity)
		{
			this.SendPropertyChanging();
			entity.bophannv = this;
		}
		
		private void detach_thukhos(thukho entity)
		{
			this.SendPropertyChanging();
			entity.bophannv = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hanghoa")]
	public partial class hanghoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenhang;
		
		private string _mahang;
		
		private string _tennhomhang;
		
		private string _makho;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntitySet<phieuxuat> _phieuxuats;
		
		private EntityRef<kho> _kho;
		
		private EntityRef<nhomhanghoa> _nhomhanghoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenhangChanging(string value);
    partial void OntenhangChanged();
    partial void OnmahangChanging(string value);
    partial void OnmahangChanged();
    partial void OntennhomhangChanging(string value);
    partial void OntennhomhangChanged();
    partial void OnmakhoChanging(string value);
    partial void OnmakhoChanged();
    #endregion
		
		public hanghoa()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._phieuxuats = new EntitySet<phieuxuat>(new Action<phieuxuat>(this.attach_phieuxuats), new Action<phieuxuat>(this.detach_phieuxuats));
			this._kho = default(EntityRef<kho>);
			this._nhomhanghoa = default(EntityRef<nhomhanghoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenhang", DbType="VarChar(20)")]
		public string tenhang
		{
			get
			{
				return this._tenhang;
			}
			set
			{
				if ((this._tenhang != value))
				{
					this.OntenhangChanging(value);
					this.SendPropertyChanging();
					this._tenhang = value;
					this.SendPropertyChanged("tenhang");
					this.OntenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahang", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahang
		{
			get
			{
				return this._mahang;
			}
			set
			{
				if ((this._mahang != value))
				{
					this.OnmahangChanging(value);
					this.SendPropertyChanging();
					this._mahang = value;
					this.SendPropertyChanged("mahang");
					this.OnmahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhomhang", DbType="VarChar(8)")]
		public string tennhomhang
		{
			get
			{
				return this._tennhomhang;
			}
			set
			{
				if ((this._tennhomhang != value))
				{
					if (this._nhomhanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntennhomhangChanging(value);
					this.SendPropertyChanging();
					this._tennhomhang = value;
					this.SendPropertyChanged("tennhomhang");
					this.OntennhomhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makho", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string makho
		{
			get
			{
				return this._makho;
			}
			set
			{
				if ((this._makho != value))
				{
					if (this._kho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhoChanging(value);
					this.SendPropertyChanging();
					this._makho = value;
					this.SendPropertyChanged("makho");
					this.OnmakhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hanghoa_phieunhap", Storage="_phieunhaps", ThisKey="mahang", OtherKey="mahang")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hanghoa_phieuxuat", Storage="_phieuxuats", ThisKey="mahang", OtherKey="mahang")]
		public EntitySet<phieuxuat> phieuxuats
		{
			get
			{
				return this._phieuxuats;
			}
			set
			{
				this._phieuxuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kho_hanghoa", Storage="_kho", ThisKey="makho", OtherKey="makho", IsForeignKey=true)]
		public kho kho
		{
			get
			{
				return this._kho.Entity;
			}
			set
			{
				kho previousValue = this._kho.Entity;
				if (((previousValue != value) 
							|| (this._kho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kho.Entity = null;
						previousValue.hanghoas.Remove(this);
					}
					this._kho.Entity = value;
					if ((value != null))
					{
						value.hanghoas.Add(this);
						this._makho = value.makho;
					}
					else
					{
						this._makho = default(string);
					}
					this.SendPropertyChanged("kho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomhanghoa_hanghoa", Storage="_nhomhanghoa", ThisKey="tennhomhang", OtherKey="tennhomhang", IsForeignKey=true)]
		public nhomhanghoa nhomhanghoa
		{
			get
			{
				return this._nhomhanghoa.Entity;
			}
			set
			{
				nhomhanghoa previousValue = this._nhomhanghoa.Entity;
				if (((previousValue != value) 
							|| (this._nhomhanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhomhanghoa.Entity = null;
						previousValue.hanghoas.Remove(this);
					}
					this._nhomhanghoa.Entity = value;
					if ((value != null))
					{
						value.hanghoas.Add(this);
						this._tennhomhang = value.tennhomhang;
					}
					else
					{
						this._tennhomhang = default(string);
					}
					this.SendPropertyChanged("nhomhanghoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.hanghoa = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.hanghoa = null;
		}
		
		private void attach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.hanghoa = this;
		}
		
		private void detach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.hanghoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhachhang;
		
		private string _tenkhachhang;
		
		private string _sex;
		
		private string _diachi;
		
		private EntitySet<phieuxuat> _phieuxuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    partial void OntenkhachhangChanging(string value);
    partial void OntenkhachhangChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public khachhang()
		{
			this._phieuxuats = new EntitySet<phieuxuat>(new Action<phieuxuat>(this.attach_phieuxuats), new Action<phieuxuat>(this.detach_phieuxuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this.OntenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._tenkhachhang = value;
					this.SendPropertyChanged("tenkhachhang");
					this.OntenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="VarChar(20)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieuxuat", Storage="_phieuxuats", ThisKey="makhachhang", OtherKey="makhachhang")]
		public EntitySet<phieuxuat> phieuxuats
		{
			get
			{
				return this._phieuxuats;
			}
			set
			{
				this._phieuxuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kho")]
	public partial class kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makho;
		
		private string _tenkho;
		
		private EntitySet<hanghoa> _hanghoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhoChanging(string value);
    partial void OnmakhoChanged();
    partial void OntenkhoChanging(string value);
    partial void OntenkhoChanged();
    #endregion
		
		public kho()
		{
			this._hanghoas = new EntitySet<hanghoa>(new Action<hanghoa>(this.attach_hanghoas), new Action<hanghoa>(this.detach_hanghoas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makho", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makho
		{
			get
			{
				return this._makho;
			}
			set
			{
				if ((this._makho != value))
				{
					this.OnmakhoChanging(value);
					this.SendPropertyChanging();
					this._makho = value;
					this.SendPropertyChanged("makho");
					this.OnmakhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkho", DbType="VarChar(20)")]
		public string tenkho
		{
			get
			{
				return this._tenkho;
			}
			set
			{
				if ((this._tenkho != value))
				{
					this.OntenkhoChanging(value);
					this.SendPropertyChanging();
					this._tenkho = value;
					this.SendPropertyChanged("tenkho");
					this.OntenkhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kho_hanghoa", Storage="_hanghoas", ThisKey="makho", OtherKey="makho")]
		public EntitySet<hanghoa> hanghoas
		{
			get
			{
				return this._hanghoas;
			}
			set
			{
				this._hanghoas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hanghoas(hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.kho = this;
		}
		
		private void detach_hanghoas(hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.kho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhacungcap")]
	public partial class nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mancc;
		
		private string _tenncc;
		
		private string _diachincc;
		
		private string _sotk;
		
		private EntitySet<phieunhap> _phieunhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanccChanging(string value);
    partial void OnmanccChanged();
    partial void OntennccChanging(string value);
    partial void OntennccChanged();
    partial void OndiachinccChanging(string value);
    partial void OndiachinccChanged();
    partial void OnsotkChanging(string value);
    partial void OnsotkChanged();
    #endregion
		
		public nhacungcap()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenncc", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tenncc
		{
			get
			{
				return this._tenncc;
			}
			set
			{
				if ((this._tenncc != value))
				{
					this.OntennccChanging(value);
					this.SendPropertyChanging();
					this._tenncc = value;
					this.SendPropertyChanged("tenncc");
					this.OntennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachincc", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string diachincc
		{
			get
			{
				return this._diachincc;
			}
			set
			{
				if ((this._diachincc != value))
				{
					this.OndiachinccChanging(value);
					this.SendPropertyChanging();
					this._diachincc = value;
					this.SendPropertyChanged("diachincc");
					this.OndiachinccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotk", DbType="VarChar(12)")]
		public string sotk
		{
			get
			{
				return this._sotk;
			}
			set
			{
				if ((this._sotk != value))
				{
					this.OnsotkChanging(value);
					this.SendPropertyChanging();
					this._sotk = value;
					this.SendPropertyChanged("sotk");
					this.OnsotkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_phieunhaps", ThisKey="mancc", OtherKey="mancc")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhomhanghoa")]
	public partial class nhomhanghoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tennhomhang;
		
		private EntitySet<hanghoa> _hanghoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntennhomhangChanging(string value);
    partial void OntennhomhangChanged();
    #endregion
		
		public nhomhanghoa()
		{
			this._hanghoas = new EntitySet<hanghoa>(new Action<hanghoa>(this.attach_hanghoas), new Action<hanghoa>(this.detach_hanghoas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhomhang", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tennhomhang
		{
			get
			{
				return this._tennhomhang;
			}
			set
			{
				if ((this._tennhomhang != value))
				{
					this.OntennhomhangChanging(value);
					this.SendPropertyChanging();
					this._tennhomhang = value;
					this.SendPropertyChanged("tennhomhang");
					this.OntennhomhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhomhanghoa_hanghoa", Storage="_hanghoas", ThisKey="tennhomhang", OtherKey="tennhomhang")]
		public EntitySet<hanghoa> hanghoas
		{
			get
			{
				return this._hanghoas;
			}
			set
			{
				this._hanghoas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hanghoas(hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.nhomhanghoa = this;
		}
		
		private void detach_hanghoas(hanghoa entity)
		{
			this.SendPropertyChanging();
			entity.nhomhanghoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieunhap;
		
		private System.DateTime _ngaynhap;
		
		private string _mathukho;
		
		private string _mancc;
		
		private System.Nullable<int> _soluong;
		
		private string _mahang;
		
		private EntityRef<hanghoa> _hanghoa;
		
		private EntityRef<nhacungcap> _nhacungcap;
		
		private EntityRef<thukho> _thukho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieunhapChanging(string value);
    partial void OnmaphieunhapChanged();
    partial void OnngaynhapChanging(System.DateTime value);
    partial void OnngaynhapChanged();
    partial void OnmathukhoChanging(string value);
    partial void OnmathukhoChanged();
    partial void OnmanccChanging(string value);
    partial void OnmanccChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnmahangChanging(string value);
    partial void OnmahangChanged();
    #endregion
		
		public phieunhap()
		{
			this._hanghoa = default(EntityRef<hanghoa>);
			this._nhacungcap = default(EntityRef<nhacungcap>);
			this._thukho = default(EntityRef<thukho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieunhap", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieunhap
		{
			get
			{
				return this._maphieunhap;
			}
			set
			{
				if ((this._maphieunhap != value))
				{
					this.OnmaphieunhapChanging(value);
					this.SendPropertyChanging();
					this._maphieunhap = value;
					this.SendPropertyChanged("maphieunhap");
					this.OnmaphieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date NOT NULL")]
		public System.DateTime ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathukho", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mathukho
		{
			get
			{
				return this._mathukho;
			}
			set
			{
				if ((this._mathukho != value))
				{
					if (this._thukho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmathukhoChanging(value);
					this.SendPropertyChanging();
					this._mathukho = value;
					this.SendPropertyChanged("mathukho");
					this.OnmathukhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					if (this._nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahang", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mahang
		{
			get
			{
				return this._mahang;
			}
			set
			{
				if ((this._mahang != value))
				{
					if (this._hanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahangChanging(value);
					this.SendPropertyChanging();
					this._mahang = value;
					this.SendPropertyChanged("mahang");
					this.OnmahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hanghoa_phieunhap", Storage="_hanghoa", ThisKey="mahang", OtherKey="mahang", IsForeignKey=true)]
		public hanghoa hanghoa
		{
			get
			{
				return this._hanghoa.Entity;
			}
			set
			{
				hanghoa previousValue = this._hanghoa.Entity;
				if (((previousValue != value) 
							|| (this._hanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hanghoa.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._hanghoa.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._mahang = value.mahang;
					}
					else
					{
						this._mahang = default(string);
					}
					this.SendPropertyChanged("hanghoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_nhacungcap", ThisKey="mancc", OtherKey="mancc", IsForeignKey=true)]
		public nhacungcap nhacungcap
		{
			get
			{
				return this._nhacungcap.Entity;
			}
			set
			{
				nhacungcap previousValue = this._nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhacungcap.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhacungcap.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._mancc = value.mancc;
					}
					else
					{
						this._mancc = default(string);
					}
					this.SendPropertyChanged("nhacungcap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thukho_phieunhap", Storage="_thukho", ThisKey="mathukho", OtherKey="mathukho", IsForeignKey=true)]
		public thukho thukho
		{
			get
			{
				return this._thukho.Entity;
			}
			set
			{
				thukho previousValue = this._thukho.Entity;
				if (((previousValue != value) 
							|| (this._thukho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._thukho.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._thukho.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._mathukho = value.mathukho;
					}
					else
					{
						this._mathukho = default(string);
					}
					this.SendPropertyChanged("thukho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieuxuat")]
	public partial class phieuxuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieuxuat;
		
		private System.DateTime _ngayxuat;
		
		private string _mathukho;
		
		private string _mahang;
		
		private System.Nullable<int> _soluong;
		
		private string _makhachhang;
		
		private EntityRef<hanghoa> _hanghoa;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<thukho> _thukho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieuxuatChanging(string value);
    partial void OnmaphieuxuatChanged();
    partial void OnngayxuatChanging(System.DateTime value);
    partial void OnngayxuatChanged();
    partial void OnmathukhoChanging(string value);
    partial void OnmathukhoChanged();
    partial void OnmahangChanging(string value);
    partial void OnmahangChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    #endregion
		
		public phieuxuat()
		{
			this._hanghoa = default(EntityRef<hanghoa>);
			this._khachhang = default(EntityRef<khachhang>);
			this._thukho = default(EntityRef<thukho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieuxuat", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieuxuat
		{
			get
			{
				return this._maphieuxuat;
			}
			set
			{
				if ((this._maphieuxuat != value))
				{
					this.OnmaphieuxuatChanging(value);
					this.SendPropertyChanging();
					this._maphieuxuat = value;
					this.SendPropertyChanged("maphieuxuat");
					this.OnmaphieuxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuat", DbType="Date NOT NULL")]
		public System.DateTime ngayxuat
		{
			get
			{
				return this._ngayxuat;
			}
			set
			{
				if ((this._ngayxuat != value))
				{
					this.OnngayxuatChanging(value);
					this.SendPropertyChanging();
					this._ngayxuat = value;
					this.SendPropertyChanged("ngayxuat");
					this.OnngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathukho", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mathukho
		{
			get
			{
				return this._mathukho;
			}
			set
			{
				if ((this._mathukho != value))
				{
					if (this._thukho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmathukhoChanging(value);
					this.SendPropertyChanging();
					this._mathukho = value;
					this.SendPropertyChanged("mathukho");
					this.OnmathukhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahang", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mahang
		{
			get
			{
				return this._mahang;
			}
			set
			{
				if ((this._mahang != value))
				{
					if (this._hanghoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahangChanging(value);
					this.SendPropertyChanging();
					this._mahang = value;
					this.SendPropertyChanged("mahang");
					this.OnmahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hanghoa_phieuxuat", Storage="_hanghoa", ThisKey="mahang", OtherKey="mahang", IsForeignKey=true)]
		public hanghoa hanghoa
		{
			get
			{
				return this._hanghoa.Entity;
			}
			set
			{
				hanghoa previousValue = this._hanghoa.Entity;
				if (((previousValue != value) 
							|| (this._hanghoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hanghoa.Entity = null;
						previousValue.phieuxuats.Remove(this);
					}
					this._hanghoa.Entity = value;
					if ((value != null))
					{
						value.phieuxuats.Add(this);
						this._mahang = value.mahang;
					}
					else
					{
						this._mahang = default(string);
					}
					this.SendPropertyChanged("hanghoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieuxuat", Storage="_khachhang", ThisKey="makhachhang", OtherKey="makhachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.phieuxuats.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.phieuxuats.Add(this);
						this._makhachhang = value.makhachhang;
					}
					else
					{
						this._makhachhang = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thukho_phieuxuat", Storage="_thukho", ThisKey="mathukho", OtherKey="mathukho", IsForeignKey=true)]
		public thukho thukho
		{
			get
			{
				return this._thukho.Entity;
			}
			set
			{
				thukho previousValue = this._thukho.Entity;
				if (((previousValue != value) 
							|| (this._thukho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._thukho.Entity = null;
						previousValue.phieuxuats.Remove(this);
					}
					this._thukho.Entity = value;
					if ((value != null))
					{
						value.phieuxuats.Add(this);
						this._mathukho = value.mathukho;
					}
					else
					{
						this._mathukho = default(string);
					}
					this.SendPropertyChanged("thukho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thukho")]
	public partial class thukho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mathukho;
		
		private string _tenthukho;
		
		private string _diachi;
		
		private string _sex;
		
		private string _mabophan;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntitySet<phieuxuat> _phieuxuats;
		
		private EntityRef<bophannv> _bophannv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmathukhoChanging(string value);
    partial void OnmathukhoChanged();
    partial void OntenthukhoChanging(string value);
    partial void OntenthukhoChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnmabophanChanging(string value);
    partial void OnmabophanChanged();
    #endregion
		
		public thukho()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._phieuxuats = new EntitySet<phieuxuat>(new Action<phieuxuat>(this.attach_phieuxuats), new Action<phieuxuat>(this.detach_phieuxuats));
			this._bophannv = default(EntityRef<bophannv>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathukho", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mathukho
		{
			get
			{
				return this._mathukho;
			}
			set
			{
				if ((this._mathukho != value))
				{
					this.OnmathukhoChanging(value);
					this.SendPropertyChanging();
					this._mathukho = value;
					this.SendPropertyChanged("mathukho");
					this.OnmathukhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenthukho", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tenthukho
		{
			get
			{
				return this._tenthukho;
			}
			set
			{
				if ((this._tenthukho != value))
				{
					this.OntenthukhoChanging(value);
					this.SendPropertyChanging();
					this._tenthukho = value;
					this.SendPropertyChanged("tenthukho");
					this.OntenthukhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="VarChar(20)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabophan", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string mabophan
		{
			get
			{
				return this._mabophan;
			}
			set
			{
				if ((this._mabophan != value))
				{
					if (this._bophannv.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmabophanChanging(value);
					this.SendPropertyChanging();
					this._mabophan = value;
					this.SendPropertyChanged("mabophan");
					this.OnmabophanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thukho_phieunhap", Storage="_phieunhaps", ThisKey="mathukho", OtherKey="mathukho")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thukho_phieuxuat", Storage="_phieuxuats", ThisKey="mathukho", OtherKey="mathukho")]
		public EntitySet<phieuxuat> phieuxuats
		{
			get
			{
				return this._phieuxuats;
			}
			set
			{
				this._phieuxuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bophannv_thukho", Storage="_bophannv", ThisKey="mabophan", OtherKey="mabophan", IsForeignKey=true)]
		public bophannv bophannv
		{
			get
			{
				return this._bophannv.Entity;
			}
			set
			{
				bophannv previousValue = this._bophannv.Entity;
				if (((previousValue != value) 
							|| (this._bophannv.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bophannv.Entity = null;
						previousValue.thukhos.Remove(this);
					}
					this._bophannv.Entity = value;
					if ((value != null))
					{
						value.thukhos.Add(this);
						this._mabophan = value.mabophan;
					}
					else
					{
						this._mabophan = default(string);
					}
					this.SendPropertyChanged("bophannv");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.thukho = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.thukho = null;
		}
		
		private void attach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.thukho = this;
		}
		
		private void detach_phieuxuats(phieuxuat entity)
		{
			this.SendPropertyChanging();
			entity.thukho = null;
		}
	}
}
#pragma warning restore 1591
